#!/bin/sh
# PSP Software Development Kit - http://www.pspdev.org
# -----------------------------------------------------------------------
# Licensed under the BSD license, see LICENSE in PSPSDK root for details.
#
# bootstrap - Script to bootstrap GNU autoconf and GNU automake.
#             Inspired by libtool's autogen script.
#
# Copyright (c) 2005 Marcus R. Brown <mrbrown@ocgnet.org>
# Copyright (c) 2005 James Forshaw <tyranid@gmail.com>
# Copyright (c) 2005 John Kelley <ps2dev@kelley.ca>
#$Id: bootstrap 444 2005-07-03 20:34:12Z mrbrown $

top_srcdir=`dirname $0`

version=`cat "$top_srcdir/VERSION"`
cat configure | sed "s/\<XREADER_VERSION\>/$version/g" > configure.out
cp configure.out configure
rm -f configure.out

version=`cat "$top_srcdir/VERNUM"`
cat configure | sed "s/\<XREADER_VERSION_NUMBER\>/$version/g" > configure.out
cp configure.out configure
rm -f configure.out

sh Revision.sh
