#ifndef _VERSION_H_
#define _VERSION_H_

#define EREADER_VERSION_NUM 0x010509C0
#define EREADER_VERSION_SHORT "1.60"
#define EREADER_VERSION_LONG "1.6.0.200 Built "  __TIME__ " " __DATE__ " (hrimfaxi ×ÔÖÆ°æ)"
#define EREADER_VERSION_STR_SHORT "xReader " EREADER_VERSION_SHORT
#define EREADER_VERSION_STR_LONG "xReader " EREADER_VERSION_LONG

#endif
